CREATE TABLE IF NOT EXISTS paste (
    id serial PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    body TEXT NOT NULL,
    hash VARCHAR(97) UNIQUE NOT NULL,
    language VARCHAR(50) UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
)
